spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebookstoredb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

ebookstore:
  coverPhotosPath: coverPhotos/

base:
  url: http://localhost:8080
